name: Feature Request
description: Feature Request
labels:
  - Feature
title: "[Feature Request] Your feature request title here"
body:
  - type: textarea
    attributes:
      label: Description
      description: Please provide a concise description of what you are requesting.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this feature important? What problem does it solve?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Please provide any additional information that you think may be helpful.
    validations:
      required: false
